import Head from "next/head";
import Header from "./header";
import styles from "../styles/Layout.module.scss";

export default function Layout({ children, pageTitle }) {
  return (
    <>
      <Header title="Welcome!" />
      <div className={styles.container}>
        <Head>
          <title>{pageTitle}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>{children}</main>
      </div>
    </>
  );
}
