import Head from "next/head";
import Header from "./header";
import Footer from "./footer";
import DarkModeButton from "./darkModeButton";
import styles from "../styles/Layout.module.scss";

export default function Layout({
  children,
  pageTitle,
  noHeader = false,
  noFooter = false,
  noDarkModeButton = false,
}) {
  return (
    <div className={`${styles.container} flex flex-column`}>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {noHeader ? null : <Header title={pageTitle} />}
      <div className={styles.mainContainer}>
        <main className={styles.main}>{children}</main>
      </div>
      {noFooter ? null : <Footer />}
      {noDarkModeButton ? null : <DarkModeButton />}
    </div>
  );
}
