import Head from "next/head";
import { useEffect } from "react";
import Header from "./header";
import Footer from "./footer";
import DarkModeButton from "./darkModeButton";
import Sidebar from "./sidebar";
import { initialTheme } from "../lib/themeControl";
import styles from "../styles/Layout.module.scss";
import { siteTitle } from "../env/vars.json";

export default function Layout({
  children,
  home = false,
  pageTitle = null,
  noHeader = false,
  noFooter = false,
  noDarkModeButton = false,
  plainCookies = null,
  plain = null,
  theme = null,
}) {
  useEffect(() => {
    initialTheme();
  });

  return (
    <div id="bgContainer">
      <div id="container" className={`${styles.container} flex flex-column`}>
        <Head>
          <title>{home ? siteTitle : pageTitle + " | Hack Util Apps"}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {noHeader ? null : <Header title={pageTitle} />}
        <Sidebar />
        <div className={styles.mainContainer}>
          {noDarkModeButton ? null : <DarkModeButton />}
          <main className={styles.main}>{children}</main>
        </div>
        {noFooter ? null : <Footer />}
      </div>
    </div>
  );
}
